export const GAME_JOIN = 'socket/game:join';
export const GAME_READY = 'socket/game:ready';
export const GAME_JOINED = 'socket/game:joined';
export const GAME_LEAVED = 'socket/game:leaved';
export const GAME_START = 'socket/game:start';
export const GAME_YOUR_TURN = 'socket/game:your turn';
export const GAME_HIS_TURN = 'socket/game:his turn';
export const GAME_PUT_PIECE = 'socket/game:put piece';
export const GAME_PIECE_SET = 'socket/game:piece set';
